apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:05:24Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5040"
  uid: 0216a611-7eb8-4880-be96-d34a48c37dd8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.248.117
  clusterIPs:
  - 10.105.248.117
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30615
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
